### PR TITLE
GUI-2246 don't parse/dump template text when viewing template

### PR DESCRIPTION
**Pull request by dkavanagh**
don't parse/dump template text when viewing template

https://eucalyptus.atlassian.net/browse/GUI-2246

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1230/
Test FAILed.

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1231/
Test FAILed.

**Comment by aliceh** [comment]
@dkavanagh bucket test will not pass in this branch because @coyote240  had to introduce some changes into eucaconsole such as giving a name to upload window to write the sequence. These changes did not get into 4.2.1, apparently. I recommend merging code added in  GUI-2112 (S3 sequence epic) into maint-4.2

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1237/
Test FAILed.

**Comment by dkavanagh** [comment]
Still trying to get this branch to pass bucket tests, but since this branch had nothing to do with bucket changes, is that kind of a high bar to expect it to fix when the actual code change is so very minor? @aliceh

**Pull request closed without merging**
