### PR TITLE
GUI-1913 Update notification styles.

### PR DESCRIPTION
**Pull request by coyote240**
https://eucalyptus.atlassian.net/browse/GUI-1913

### CODE REVIEW

**Comment by dkavanagh** [comment]
wow, they look just like Jira's!

**Comment by coyote240** [comment]
@dkavanagh Certainly inspired by :-)

**Comment by dkavanagh** [comment]
I think this needs more work w/ media queries. Small breakpoint has text flowing outside the box, Medium is pretty narrow and likely needs to be a wider percentage.

**Comment by coyote240** [comment]
Good call.  I can address this.

**Comment by coyote240** [comment]
@dkavanagh Breakpoints added.

**Comment by dkavanagh** [comment]
Works a lot better!

**Pull request merged**
