### PR TITLE
Gui 2061 paring down

### PR DESCRIPTION
**Pull request by dkavanagh**

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1225/
Test FAILed.

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1226/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1227/
Test PASSed.

**Comment by dkavanagh** [comment]
whohoo! Now to see why this small change made it pass.

**Pull request closed without merging**
