### PR TITLE
GUI-1474 updated navigation to always use hamburger

### PR DESCRIPTION
**Pull request by dkavanagh**
updated navigation to always use hamburger

https://eucalyptus.atlassian.net/browse/GUI-1474

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test Failed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/62/
Test Failed.

**Comment by aliceh** [comment]
euca-qa-gui-tester, retest this please

**Comment by aliceh** [comment]
retest this please

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/63/
Test PASSed.

**Comment by kamalgill** [comment]
@dkavanagh: I had to re-trigger the Travis tests a few times to get them to pass, so we should be good to merge this after resolving the conflicts.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/75/
Test FAILed.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/76/
Test PASSed.

**Pull request merged**
