### PR TITLE
GUI-1481: Leverage Bower for Zurb Foundation dependency management

### PR DESCRIPTION
**Pull request by kamalgill**
References https://eucalyptus.atlassian.net/browse/GUI-1481

Pin Foundation to 5.0.3, managed via Bower.  

Note: We have been using Foundation 5.0.3 in the 4.0 and 4.1 release of the console.  This PR doesn't update the Foundation version, it simply leverages Bower to manage the dependencies (Sass and JS files).  We have GUI-1478 to track updating Foundation, but implementing GUI-1481 first makes that upgrade process a lot easier to test and potentially revert.

The critical files to review here are Gruntfile.js, bower.json, and magic_search.html.  The magic search bar template fixes should be ported to the external magic search bar repo if they haven't already.

### CODE REVIEW

**Comment by dkavanagh** [comment]
Lots of changes. Looks like we didn't quite have 5.0.3 in our repo. Hopefully bower will keep the files updated more fully. nothing breaks with this?

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/78/
Test PASSed.

**Comment by kamalgill** [comment]
@dkavanagh: We did have 5.0.3, but there seemed to be quite a few diffs between the Bower-installed 5.0.3 and the 5.0.3 tarball downloaded a while ago from the Foundation site.  I can't guarantee nothing is broken with this, but we'll fix any issues as they surface.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/79/
Test FAILed.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/80/
Test FAILed.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Grr, Jenkins is failing at the problematic "delete-volume-on-detail-page" test, which has nothing to do with the changes here.  Since the prior CI build at http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/78/ passed, and the latest change is a CSS alignment fix for the login page, this PR should be safe to merge after it passed code review.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/82/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
@kamalgill, I submitted a patch for this in https://github.com/eucalyptus/eucaconsole/pull/1309... the branch being tested here must have been created before my patch was merged.

**Pull request merged**
