### PR TITLE
IAM Test Modifications

### PR DESCRIPTION
**Pull request by ccassler**
Tested on selenium RC and IDE

### CODE REVIEW

**Comment by kyolee310** [comment]
Can one of the admins verify this patch?

**Comment by kyolee310** [comment]
ok to test.

**Comment by aliceh** [comment]
This change only concerns the IAM tests, not tests running on PR.

**Comment by aliceh** [comment]
Thanks @ccassler !

**Comment by kyolee310** [comment]
No need for running the PR monitor test since no IAM test is currently running by the PR monitor instance.

**Pull request merged**
