### PR TITLE
GUI-1518: Fix attaching volume to instance on volumes landing page

### PR DESCRIPTION
**Pull request by kamalgill**
Fixes https://eucalyptus.atlassian.net/browse/GUI-1518

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/125/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/127/
Test FAILed.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/128/
Test FAILed.

**Comment by kyolee310** [comment]
Good to merge once it passes the automated test.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Found an issue with the form validation logic.  Closing this PR for now, will reopen after a proper fix is in place.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/129/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/130/
Test PASSed.

**Pull request merged**
