### PR TITLE
GUI-2486 added missing monitor options on instance landing

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-2486

### CODE REVIEW

**Comment by kamalgill** [comment]
Retest this, please

**Comment by aliceh** [comment]
Retest this please

**Comment by dkavanagh** [comment]
Retest this please

**Comment by aliceh** [comment]
@dkavanagh  the tests on this branch are failing in the same places over and over. I bet there is a bug there. Please try running the instance, volume, snapshot or eip tests to see what it is.  If you don't have time to do it, let me know and I'll check it for you.

**Comment by dkavanagh** [comment]
instance test fail at:
ERROR: Could not perform click on element by id = ('terminate_instance_submit_button')
volume, same
ERROR: Did not find clickable element by id = 'terminate_instance_submit_button'
snapshot,
ERROR: Could not perform click on element by id = ('terminate_instance_submit_button')
sensing a trend from a single problem. I'll see if adding a menu option in the instances menu caused this. Seems like the test must be using an index rather than ID.

**Comment by dkavanagh** [comment]
\o/

**Pull request merged**
