### PR TITLE
Gui 1636 update help and action menu icons

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-1636

note: this now includes GUI-1489 to get tests working on this branch. Once that is merged to master, the diffs for this branch will be more accurate.

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/180/
Test FAILed.

**Comment by kamalgill** [comment]
@dkavanagh: Please back out the errant import statement, which ballooned the landing page and dashboard CSS files by over 1100 lines.  We should reference the font awesome CSS file in the master template instead.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/184/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/185/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/186/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/191/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/195/
Test PASSed.

**Comment by kamalgill** [comment]
@dkavanagh: Closing w/o merging.  Please reopen this PR after the selenium nav test fixes have been pull out and moved to a distinct PR.

**Pull request closed without merging**
