### PR TITLE
GUI-2497: Consolidate ssl context patch and handle missing 'context' kwarg for httplib.HTTPSConnection in Python < 2.7.9

### PR DESCRIPTION
**Pull request by kamalgill**
Proper fix for https://eucalyptus.atlassian.net/browse/GUI-2497

### CODE REVIEW

**Comment by kamalgill** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this, please

**Comment by aliceh** [comment]
Retest this, please

**Comment by aliceh** [comment]
@kamalgill I tested in CI (twice) good to merge!

**Pull request merged**
