### PR TITLE
GUI-1146 added meta refresh tag to reload page every 29 minutes

### PR DESCRIPTION
**Pull request by dkavanagh**
added meta refresh tag to reload page every 29 minutes

https://eucalyptus.atlassian.net/browse/GUI-1146

### CODE REVIEW

**Comment by kamalgill** [comment]
@dkavanagh: Instead of hard-coding the refresh to every 29 minutes, we should set the refresh interval based on the `session.timeout` value from console.ini since it's configurable.  Perhaps set the refresh interval to `session.timeout - 60` seconds?

**Comment by dkavanagh** [comment]
I'll have to test to verify the session.timeout is what's affecting the csrf token expiration first.

**Comment by kamalgill** [comment]
@dkavanagh: The `session.timeout` value specifies the idle timeout duration, which is what GUI-1146 covers AFAICT.

**Comment by dkavanagh** [comment]
Well, we know the idle timeout is non-functional since the app will log you out during usage. I'm not making any assumptions without verifying.

**Comment by dkavanagh** [comment]
I was able to verify that the session.timeout is directly related to how often the login becomes non-functional, so I'll use a value that's 60 seconds less than session.timeout.

**Pull request merged**
