### PR TITLE
Gui 2164 pass progress from task to image, fix progress bar look

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-2164

### CODE REVIEW

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by dkavanagh** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by aliceh** [comment]
@kamalgill  I looked at the log where the instance test fails and it looks like in the launch instance wizard after a centos image is found via image filter, the tester can not find css = '[class='grid-action']' which used to be the locator for the "select" button next to the instance. Please check if there changes in the code that would affect  the above locator and update the test code if needed. Here is a part of the log showing failure. 

Element by css = '.search-input' was located in DOM and is visible.
Clearing field by css = '.search-input'
Typing text 'centos' into field by css = '.search-input'
Executing wait_for_visible_by_css('[class='grid-action']'), timeout_in_seconds is set to 60
ERROR: Timed out: element by css = '[class='grid-action']' not visible.
Checking whether element by css = '[class='grid-action']' present in the DOM.

**Comment by dkavanagh** [comment]
@aliceh this code clearly doesn't touch anything related to the image selector or launch instance wizard.

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by kamalgill** [comment]
Jenkins build has passed ... http://jenkins.qa1.eucalyptus-systems.com/view/Eucaconsole%20CI/job/user-console-PR-monitor/1129/

**Pull request merged**
