### PR TITLE
GUI-1629: Prevent CSP violations by removing unneeded JS on the About the Team page

### PR DESCRIPTION
**Pull request by kamalgill**
Fixes https://eucalyptus.atlassian.net/browse/GUI-1629

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/93/
Test FAILed.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/96/
Test PASSed.

**Comment by dkavanagh** [comment]
FWIW, these were leftovers from older code on the page that operated a "close" button, but was removed due to CSP issues.

**Pull request merged**
