### PR TITLE
GUI-2161: Remove M2Crypto version cap

### PR DESCRIPTION
**Pull request by kamalgill**
https://eucalyptus.atlassian.net/browse/GUI-2161

### CODE REVIEW

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by dkavanagh** [comment]
This PR fails CI when trying to install m2crypto. Probably need to verify new version by hand first?

**Comment by aliceh** [comment]
there is a problem with console install from this branch, see the logs:


building 'M2Crypto.__m2crypto' extension

swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c

swig -python -I/usr/include/python2.6 -I/usr/include -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.6/M2Crypto -D__x86_64__ -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i

swig error : Unrecognized option -builtin

Use 'swig -help' for available options.

error: command 'swig' failed with exit status 1

**Comment by aliceh** [comment]
Retest this, please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1143/
Test PASSed.

**Pull request merged**
