### PR TITLE
GUI-2279 Integrate tag-editor directive into image detail page.

### PR DESCRIPTION
**Pull request by coyote240**
https://eucalyptus.atlassian.net/browse/GUI-2279

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1245/
Test PASSed.

**Comment by coyote240** [comment]
Please note that this PR merges into GUI-2277 and not master due to dependencies.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1253/
Test PASSed.

**Comment by coyote240** [comment]
Closing as target branch has been merged.  Creating new PR.

**Pull request closed without merging**
