### PR TITLE
GUI-1678 fixed display_path for bucket/folders

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-1678

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/233/
Test PASSed.

**Comment by kamalgill** [comment]
@dkavanagh: PR looks good, but I'd really like to see a unit test for this.  We should add two tests, one for all items in a bucket, and the other for all items in a folder.

**Comment by dkavanagh** [comment]
@kamalgill What are you suggesting we test for?

**Comment by kamalgill** [comment]
@dkavanagh: This is a good chance to leverage moto for unit tests here.  I'll go ahead and merge the PR for GUI-1417 and write a couple of tests, which we can cover during our next dev sync-up.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/244/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/245/
Test PASSed.

**Comment by dkavanagh** [comment]
@kamalgill  "python setup.py test" returns an error "object has no attribute 'test_bucket'"

**Pull request merged**
