### PR TITLE
GUI-2360 implement stack update

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-2360

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1596/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1599/
Test FAILed.

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by kamalgill** [comment]
Closing due to errant commit https://github.com/eucalyptus/eucaconsole/commit/cc629d0025fc5c51e5c25752049ba511bba3a428

Will open a separate PR without that commit.

**Comment by kamalgill** [comment]
Supplanted by https://github.com/eucalyptus/eucaconsole/pull/1832

**Pull request closed without merging**
