### PR TITLE
Updated more go to tab methods to deal with names in all caps

### PR DESCRIPTION
**Pull request by aliceh**

### CODE REVIEW

**Comment by kamalgill** [comment]
We should really do case insensitive checks for tab names and other labels if possible.

**Comment by aliceh** [comment]
@kamalgill should I prepare a PR with a case-sensitive check?

**Comment by aliceh** [comment]
@kamalgill, sorry misread your comment X-)

**Comment by aliceh** [comment]
@kamalgill or @dkavanagh, could one of you please merge this PR? Should I prepare another PR to address the same issue for 5.0 or can we merge maint-4.4 into 5.0 branch?

**Pull request merged**
