### PR TITLE
DOC-1553: new console help topics for stack pages.

### PR DESCRIPTION
**Pull request by tvo318**
Please merge approved content for stack pages.

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/230/
Test PASSed.

**Comment by kamalgill** [comment]
https://eucalyptus.atlassian.net/browse/DOC-1553

**Comment by tvo318** [comment]
How do these help files get attached to their pages?

**Comment by dkavanagh** [comment]
yea, this should have been passed to me to link the pages. I'll update in GUI-1489 with a bunch of other stack updates.

**Comment by tvo318** [comment]
Thank you David!!

**Comment by kamalgill** [comment]
@dkavanagh: We should discuss how to handle our doc workflow, perhaps during the team meeting.  I think it makes sense to use the GUI ticket to wire up the help pages, with the DOC ticket merely providing the help pages and marked as a blocking ticket for the GUI ticket.  This workflow is similar to our new UX workflow where UX wireframe tickets block their respective GUI tickets.

**Pull request merged**
