### PR TITLE
GUI-2204 split help on tabbed screens that weren't already

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-2204

### CODE REVIEW

**Comment by kamalgill** [comment]
Jenkins build has passed for https://github.com/eucalyptus/eucaconsole/commit/d2bd713f1fb593209cd0f1a4b179920889343b5f ... http://jenkins.qa1.eucalyptus-systems.com/view/Eucaconsole%20CI/job/user-console-PR-monitor/1128/

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1152/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1155/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1156/
Test PASSed.

**Pull request merged**
