### PR TITLE
GUI-1478: Update Foundation to 5.5.1

### PR DESCRIPTION
**Pull request by kamalgill**
Implements https://eucalyptus.atlassian.net/browse/GUI-1478

Note that after this is merged to master, compiling Sass to CSS (via compass watch) will require version bumps for Ruby-based Sass and Compass on each development environment.  See the relevant section in README.rst for details

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/95/
Test FAILed.

**Comment by kamalgill** [comment]
@aliceh: Jenkins build 95 reports two non-deterministic failures, one is the pesky "delete-volume-from-lp" test, and the other is the "verify-instance-is-terminated" test.  I'm unable to reproduce those failures locally so will re-trigger this PR, but is there anything we can do to address those problematic tests?

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
@kamalgill I submitted a patch into mater https://eucalyptus.atlassian.net/browse/GUI-1626. Can you try and pull in this code?

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/98/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/99/
Test FAILed.

**Comment by kamalgill** [comment]
@aliceh: I merged from master but build 99 failed, this time on the "delete-volume-from-lp" test, which I'm unable to reproduce locally.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
@kamalgill , note that verify-keypair-was-deleted.html fails because it fails to find id=search-input.
This test uses search bar to verify key pair was deleted. Since the old search bar was replaced with magic search the person who committed the changes should also fix the above test.

**Comment by euca-qa-gui-tester** [comment]
I removed the step that gets notification in delete-volume-from-detail-page.html test https://github.com/eucalyptus/eucaconsole/pull/1319

**Comment by aliceh** [comment]
@kamalgill I just checked the the verify-keypair-was-deleted.html test with 4.2 console and it should not be failing. I will remove search from test logic.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/100/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/134/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/135/
Test FAILed.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/137/
Test PASSed.

**Pull request merged**
