### PR TITLE
Added storeTextIfPresent operation and a condition to delete-volume-on-detail-page test for it to pass if deleted volume is removed from landing page

### PR DESCRIPTION
**Pull request by aliceh**

### CODE REVIEW

**Comment by aliceh** [comment]
Please don't delete branch after merge: I would like to also merge these changes into master.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com:8080/job/user-console-regression-sequence//job/user-console-PR-monitor/30/
Test PASSed.

**Comment by kamalgill** [comment]
@aliceh: PR merged, branch left open.

**Comment by kamalgill** [comment]
@aliceh: Is it safe to delete the GUI-1600 branch now?

**Pull request merged**
