### PR TITLE
Gui 1684 Adjusted the security group rule panel's style

### PR DESCRIPTION
**Pull request by kyolee310**
https://eucalyptus.atlassian.net/browse/GUI-1684

### CODE REVIEW

**Comment by kyolee310** [comment]
retest please.

**Comment by kyolee310** [comment]
@aliceh could you restart this test please?

**Comment by kyolee310** [comment]
retest this please

**Comment by aliceh** [comment]
retest this please

**Comment by aliceh** [comment]
Random failure to get notification. Good to merge.

**Pull request merged**
