### PR TITLE
GUI-2120 Create dialog.

### PR DESCRIPTION
**Pull request by coyote240**
https://eucalyptus.atlassian.net/browse/GUI-2120

### CODE REVIEW

**Comment by coyote240** [comment]
Hal, retest this please.

**Comment by coyote240** [comment]
test this please

**Comment by coyote240** [comment]
Retest this, please.

**Comment by aliceh** [comment]
Guitester, retest this please

**Comment by aliceh** [comment]
@coyote240 I went and looked via VNC at the last few minutes of the test before it failed. The register snapshot as volume dialog only showed one zone.  Weirdly enough, I could not reproduce this failure outside of the test...

**Pull request closed without merging**
