### PR TITLE
GUI-2378: Avoid 500 error when creating a launch config like one with an image that's no longer available

### PR DESCRIPTION
**Pull request by kamalgill**
Fixes https://eucalyptus.atlassian.net/browse/GUI-2378

### CODE REVIEW

**Comment by aliceh** [comment]
Retest this please

**Comment by kamalgill** [comment]
Retest this please

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by dkavanagh** [comment]
@kamalgill this keeps failing in autoscaling tests. Since the changes are related, can you investigate?

**Pull request merged**
