### PR TITLE
GUI-2168 Prevent user from trying to create an admin user, update val…

### PR DESCRIPTION
**Pull request by coyote240**
…idation.

https://eucalyptus.atlassian.net/browse/GUI-2168

### CODE REVIEW

**Comment by coyote240** [comment]
Retest this, please.

**Comment by coyote240** [comment]
Retest this, please.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by aliceh** [comment]
@kamalgill  Jenkins is down.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by kamalgill** [comment]
Jenkins build has passed ... http://jenkins.qa1.eucalyptus-systems.com/view/Eucaconsole%20CI/job/user-console-PR-monitor/1123/

**Pull request merged**
