### PR TITLE
GUI-1565: Remove misleading warning when session.secure = false and console is requested via HTTPS

### PR DESCRIPTION
**Pull request by kamalgill**
...also set session.secure = true in the default console.ini file

Fixes https://eucalyptus.atlassian.net/browse/GUI-1565

### CODE REVIEW

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by aliceh** [comment]
From the log it is evident that the tester can not log in to the console. Not sure why...

**Comment by dkavanagh** [comment]
code changes are good. I can also login when running it on OS X. I can't see how this would interfere with login, but would be nice to know why tests are failing.

**Pull request merged**
