### PR TITLE
GUI-1726, flow and spacing of magic search items.

### PR DESCRIPTION
**Pull request by coyote240**
https://eucalyptus.atlassian.net/browse/GUI-1726

Just getting the process started.  I think a flex-box solution gives us the most resilient result, but must review.

### CODE REVIEW

**Comment by coyote240** [comment]
retest this, please

**Comment by aliceh** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this please

**Pull request closed without merging**
