### PR TITLE
Update eucaconsole.po

### PR DESCRIPTION
**Pull request by dmoror**
Improving and adding some Spanish text translations

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by dkavanagh** [comment]
Thanks @dmoror, that looks like you've made a start. I notice your branch is "patch-1", so do you plan on submitting subsequent patches to add more Spanish translations?

**Comment by dmoror** [comment]
Hi @dkavanagh. Yes, It's almost sure that I'll submit more patches to this translation file. Hope there's no problem with the branch name :)

**Comment by dkavanagh** [comment]
No problem at all. I just wondered if it was 1 of many. We'll have someone review. There may still be a CLA required, but I'll look into it.

**Comment by dmoror** [comment]
Great, thanks @dkavanagh. This is just my first contribution to the project, next time I'll push the rest of the file to avoid innecesary testing processes.

**Comment by miquelvidal** [comment]
Thanks Dmoror!

**Comment by kamalgill** [comment]
@dmoror: Apologies for the delay in responding to this PR.  We are reviewing our external contributor process, and you should hear from us regarding the next steps soon.  In the meantime, feel free to add the additional steps to complete the translation updates (e.g. `python setup.py compile_catalog`), per what is documented at https://github.com/eucalyptus/eucaconsole/wiki/Contributing-Translations .

**Comment by aliceh** [comment]
Test this please

**Comment by dmoror** [comment]
@kamalgill Ok, I'll try to complete the translation process ASAP. BTW, I can't see the failing check details, anyone can give that info?

**Comment by kamalgill** [comment]
@dmoror: Feel free to ignore the failing check.  We're making tweaks to our CI process (running on an internal Jenkins instance), which doesn't test i18n anyway, so the failure is safe to ignore for your contributions.

**Comment by aliceh** [comment]
@kamalgill  Merge conflict caused CI to fail

**Comment by dmoror** [comment]
Hi all, any update about this update?

**Comment by dkavanagh** [comment]
Thanks @dmoror , if you have more you'd like to contribute, we'd be happy to work with you.

**Pull request merged**
