### PR TITLE
GUI-2896: More rebranding tweaks

### PR DESCRIPTION
**Pull request by kamalgill**
https://eucalyptus.atlassian.net/browse/GUI-2896

### CODE REVIEW

**Comment by aliceh** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this please

**Comment by aliceh** [comment]
Retest this please

**Comment by dkavanagh** [comment]
merging this in spite of test failures. Changes are unrelated.

**Pull request merged**
