### PR TITLE
GUI-2297, GUI-2298: Implement sortable tables on security groups and key pairs landing pages

### PR DESCRIPTION
**Pull request by kamalgill**
Implements:
- https://eucalyptus.atlassian.net/browse/GUI-2297
- https://eucalyptus.atlassian.net/browse/GUI-2298

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1593/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1604/
Test FAILed.

**Comment by kamalgill** [comment]
Retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1609/
Test PASSed.

**Pull request merged**
