### PR TITLE
GUI-2446: Avoid wiping out selected items and automatically closing More Actions menu during smart refresh

### PR DESCRIPTION
**Pull request by kamalgill**
Fixes https://eucalyptus.atlassian.net/browse/GUI-2446

### CODE REVIEW

**Comment by dkavanagh** [comment]
I noticed when I selected the menu for the 3rd snapshot, but the 1st was in transitional state and smart refresh happened, my menu was closed and the actions menu for the 1st item was selected.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1585/
Test FAILed.

**Comment by kamalgill** [comment]
Retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1595/
Test FAILed.

**Comment by dkavanagh** [comment]
looks good to merge.

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1597/
Test PASSed.

**Pull request merged**
