### PR TITLE
GUI-2305: Implement multi-select operations on the volumes landing page

### PR DESCRIPTION
**Pull request by kamalgill**
#### Implements the following for https://eucalyptus.atlassian.net/browse/GUI-2305:
- Support the following actions in the More Actions menu when selecting a single item:  View details, Attach to instance, Manage snapshots, View Monitoring
- Allow one or more attached volumes to be detached from an instance, with a warning and list of volume/instance pairs displayed when the volume is root volume of an EBS-backed instance
- Allow one or more available volumes to be deleted

#### Refactoring for performance improvements:
- Refactors the Detach Volume dialog on the volumes landing page, volume detail page, and the instance volumes page to not require an additional XHR fetch to determine if the volume is a root volume of an EBS-backed instance

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1562/
Test FAILed.

**Comment by kamalgill** [comment]
Retest this, please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1564/
Test FAILed.

**Comment by kamalgill** [comment]
Retest this, please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1566/
Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1567/
Test FAILed.

**Comment by kamalgill** [comment]
Retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/1572/
Test PASSed.

**Pull request merged**
