### PR TITLE
GUI-2498 additional check for undefined default region

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-2498

### CODE REVIEW

**Comment by ccassler** [comment]
Retest this please

**Comment by aliceh** [comment]
The Snapshot sequence is failing, because the locator "css = '[class="chosen-single"]>span" for selecting volumes in "Create Snapshot" dialog was changed.  Please change the locator to "css=#volume_id_chosen>a" for the snapshot test to pass.

**Comment by ccassler** [comment]
@aliceh: This test was having other issues.  The GUI wasn't coming up at all.  Instead, we were seeing Internal Server Error which I noted in the ticket.

**Comment by aliceh** [comment]
@ccassler  if the console would not have been up, then the test would fail at login.

**Comment by kamalgill** [comment]
Retest this please

**Pull request merged**
