### PR TITLE
Gui 1573 updated busy indicator

### PR DESCRIPTION
**Pull request by dkavanagh**
https://eucalyptus.atlassian.net/browse/GUI-1573

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Merged build triggered.

**Comment by euca-qa-gui-tester** [comment]
Merged build started.

**Comment by euca-qa-gui-tester** [comment]
Merged build finished. Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/46/
Test PASSed.

**Comment by kamalgill** [comment]
The Travis failures are due to the JSHint failures in spec_scalinggroup.js, which have been fixed on master.  Merging from master should allow Travis to pass.

**Comment by euca-qa-gui-tester** [comment]
Merged build triggered.

**Comment by euca-qa-gui-tester** [comment]
Merged build started.

**Comment by euca-qa-gui-tester** [comment]
Merged build finished. Test PASSed.

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/50/
Test PASSed.

**Comment by dkavanagh** [comment]
Looks like things passed. Would be good to get this merged so that I can update other branches with the same changes.

**Pull request merged**
