### PR TITLE
GUI-2415: Revert to passing volume ids via filters to prevent errors w.r.t. missing volumes

### PR DESCRIPTION
**Pull request by kamalgill**
… also remove problematic unit test.

Fixes https://eucalyptus.atlassian.net/browse/GUI-2415

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1413/
Test FAILed.

**Comment by aliceh** [comment]
Retest this, please

**Comment by aliceh** [comment]
Retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/user-console-PR-monitor/1419/
Test FAILed.

**Comment by aliceh** [comment]
OK to merge

**Pull request merged**
