### PR TITLE
GUI-1675 fixed input tags to be proper html

### PR DESCRIPTION
**Pull request by dkavanagh**
fixed input tags to be proper html

https://eucalyptus.atlassian.net/browse/GUI-1675

### CODE REVIEW

**Comment by kamalgill** [comment]
@dkavanagh: What browsers did you test the fixes with?

**Comment by euca-qa-gui-tester** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com//job/user-console-PR-monitor/218/
Test PASSed.

**Comment by dkavanagh** [comment]
Since this worked in all browsers before it was proper HTML, I didn't test in more than chrome and FF

**Comment by kamalgill** [comment]
@dkavanagh: Understood, but it would be prudent to spot-check on IE since that browser tends to be less forgiving of DOM structural changes such as this one.

**Comment by dkavanagh** [comment]
I don't have a convenient way to do that. I haven't set up the VM and my windows laptop resides in a backpack. I guess if I need to verify on windows IE, I'd prefer to do a few branches at once, but getting that VM setup will help a bit.

**Comment by kamalgill** [comment]
I spot-checked on IE 11 in Edge and IE 10 mode (Windows 7 x64) and the pages look good.

**Pull request merged**
