### PR TITLE
GUI-1524: Changed regex to restrict allowable characters in key pair name

### PR DESCRIPTION
**Pull request by dkavanagh**
changed regex to restrict allowable characters

https://eucalyptus.atlassian.net/browse/GUI-1524

### CODE REVIEW

**Comment by kamalgill** [comment]
Need to search across templates for other uses of `route_path('keypair_view'`

**Comment by dkavanagh** [comment]
yes, I've done that and am fixing those.

**Comment by kamalgill** [comment]
Hal, retest this please

**Comment by dkavanagh** [comment]
Holding this for 4.1.1... closing for now.

**Pull request closed without merging**
