### PR TITLE
GUI-1958 Add URL rewrite to nginx configuration, minor README updates.

### PR DESCRIPTION
**Pull request by coyote240**
https://eucalyptus.atlassian.net/browse/GUI-1958

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by aliceh** [comment]
test this please

**Comment by aliceh** [comment]
ok to test

**Comment by dkavanagh** [comment]
hal, retest this please

**Comment by aliceh** [comment]
Guitester, retest this please.

**Pull request merged**
